name: ci

on: [push, pull_request]

jobs:
  build-with-required-deps:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.9]  #[3.4, 3.5, 3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install
        run: python setup.py install
      # - name: Tests
      #   run: |
      #     pip install tox
      #     tox -e py

  # build-with-optional-deps:
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, macos-latest, windows-latest]
  #       python-version: [3.4, 3.5, 3.6, 3.7, 3.8, 3.9]
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Setup Python
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: ${{ matrix.python }}
  #     - name: Install with optional dependencies
  #       run: |
  #         pip install regex
  #         python setup.py install
  #     - name: Tests
  #       run: |
  #         pip install nose
  #         nosetests
